stages:
  - test
  - build

cpplint:
  image: python:latest
  stage: test
  script:
    - python -m pip install cpplint
    - cpplint --filter=-whitespace,-legal/copyright,-readability/multiline_comment --linelength=180 --recursive src/* include/* &> cpplint.txt
  artifacts:
    paths:
      - cpplint.txt
  allow_failure: true

flawFinder:
  image: python:latest
  stage: test
  script:
    - python -m pip install flawfinder
    - flawfinder --html . > flawFinder.html
  artifacts:
    paths:
      - flawFinder.html
  allow_failure: true

build:
  image: python:latest
  stage: build
  only:
    - tags
  script:
    - pip install -U platformio
    - platformio run -e az-delivery-devkit-v4
    - mv .pio/build/az-delivery-devkit-v4/firmware.bin firmware-${BULD_TAG}.bin
  artifacts:
    paths:
      - firmware-${BULD_TAG}.bin
  variables:
    BULD_TAG: $CI_COMMIT_REF_NAME

build-latest:
  image: python:latest
  stage: build
  only:
    - master
  script:
    - pip install -U platformio
    - platformio run -e az-delivery-devkit-v4
    - mv .pio/build/az-delivery-devkit-v4/firmware.bin firmware-${BULD_TAG}.bin
  artifacts:
    paths:
      - firmware-${BULD_TAG}.bin
  variables:
    BULD_TAG: latest